.gitignore, src/bin/repl.rs, src/lib.rs
Make the main crate a "lib", so that it can be used as a dependency in other crates. Move the `run` functionality to `bin/repl`.
=> feat: lib/bin split

src/lib.rs, tests/edge_cases.rs
"Slice" the `chars()` iterator (using `take`) instead of slicing the underlying bytes, unfortunately there's no nice `..=` syntax here I don't think. This appears to be the only place we do this.
Can now survive fuzzing 6 (!) non-ascii bytes.
=> fix: nuuuuunez

src/lib.rs, tests/edge_cases.rs
Computers weren't meant to handle mutli-byte strings, apparently.
=> fix: nunez in strings

Cargo.lock, src/arrays.rs, src/modifiers.rs, src/scan.rs, src/verbs.rs, tests/edge_cases.rs, tests/sanity_checks.rs
`IntArray { a }` -> `IntArray(a)` seems quite a bit neater, and an annoying diff.
=> chore: anonymise array field

src/arrays.rs, src/verbs.rs, tests/sanity_checks.rs
`map_array` is just `impl_array` with `.intoto_jarray()`, which now exists.
`int_array` is a special case of `Word::noun(anything which could be made into an array)`.
`vdot` is a regular generic function!
=> chore: some macro unification

src/arrays.rs, src/verbs.rs
Follows #36.
A binary version of `impl_array`?
`promotion` now returns a `Pair` of identical arrays, and then maths operators can be implemented on `Pair`, instead of everywhere?
`v_starco` and `v_idot` also want to do this, but need to handle `chars`, and maybe don't want promotions? Maybe they do and you couldn't face it? Maybe we need a non-promoting version of homogenisation, which returns a non-maths pair, or we need to go back to a type of `char` which implements some maths operators?
Or we could stop using ops::Add::add and just "define" addition on char using.. some other trait monstrosity.
This PR doesn't actually reduce lines of code much, but it feels "correct" to me, the macros have moved "into" the enums (even though it's a new enum), and away from the "application code" (in …
=> chore: homogenising promotion

src/arrays.rs, src/modifiers.rs, src/verbs.rs, tests/edge_cases.rs
Replace some use of `unwrap` with `?`, leading to "better" errors (at least, if we fix backtraces).
=> chore: remove some unwrap

src/arrays.rs, src/lib.rs, src/verbs.rs, tests/sanity_checks.rs
Initial box implementation.
Still in progress, will require `<`, `>` and `;` implementations to be minimally useful.
See:
- https://code.jsoftware.com/wiki/Vocabulary/lt
- https://code.jsoftware.com/wiki/Vocabulary/AbsolutelyEssentialTerms#Box
- https://code.jsoftware.com/wiki/Vocabulary/Nouns#Box
- https://code.jsoftware.com/wiki/Vocabulary/aco
=> feat: BoxArray

src/arrays.rs, src/modifiers.rs
Replace one unbelievably awful macro with a *gasp* function, *gasp* regular enum and a much smaller, more familiar macro.
=> chore: split apply_array_homo into a utility struct

src/bin/jr.rs
Revert the error formatting back closer to the original format.
```
jr 0.1.0
'a','b'
error: feature not supported yet
cause: verb "," not supported
cause: evaluating 2 dyad
cause: evaluating "'a','b'\n"
```
=> feat: slightly nicer chain formatting?

src/arrays.rs, src/verbs.rs
`ArrayPair` can be Cow, which (I think?) removes an unnecessary copy during promotion in the cases where promotion doesn't happen.
I say "I think", this is then fed into `operator+` which returns a `CowArray` (which is always owned?). Maybe what we should actually be doing here is moving the first array into +, mutating it, and returning the mutated value, which isn't super compatible with this implementation. To do that you'd have to de-ref `VerbImpl::exec` and hence probably most operators, which doesn't seem worth it right now.
=> chore: ArrayPair is Cow

src/verbs.rs, tests/sanity_checks.rs
Assumes flat arrays, which is likely completely wrong.
As an example of #48.
=> feat: implement monadic behead

src/arrays/cow.rs, src/cells.rs, src/lib.rs, src/verbs/mod.rs, src/verbs/ranks.rs, tests/agreement.rs, tests/sanity_checks.rs
Wire up the "agreement" code from the #53, which isn't correct, but passes almost all of the existing tests.
`$` is broken (very, very broken), but it can be fixed by claiming it's `(inf, inf)`, bypassing the new code.
This gives us apparently-working happy path addition, multiplication, and the like, and (hopefully) slightly useful errors for the remaining insanely broken cases. From here, I propose we try and work out what is wrong with one of the functions in `cells.rs`, which are called, in order, from `exec_dyad`, which is very simple apart from error message generation.
=> feat: agreement, but wrong

Cargo.lock, examples/ranky-ranks.rs, fuzz/Cargo.lock, src/arrays/owned.rs, src/cells.rs, src/lib.rs, src/verbs/mod.rs, tests/agreement.rs
Slight code simplification (at the expense of efficiency), damaging the one (incorrect) length test, and (primarily) a test tool for comparing snippets against `jconsole`.
e.g. `PATH=$PATH:~/ins/j903 cargo run --example ranky-ranks`
=> chore: test tool

src/arrays/owned.rs, src/cells.rs, tests/agreement.rs
`choppo` is equivalent enough to `rank_iter` according to the tests, so switch to the new impl
=> rip: move choppo over to rank_iter

src/verbs/mod.rs, tests/sanity_checks.rs
Our box behaviour was wrong on atoms, the correct behaviour upstream is:
```
$ < 42
~~null~~
```
```
$ > < 42
~~null~~
```
This broke the `link` code, which I've BRUTALISED (without understanding) back to passing tests.
=> feat: boxy atoms

Cargo.lock, src/arrays/mod.rs, src/arrays/owned.rs, src/arrays/plural.rs, src/cells.rs, src/lib.rs, src/scan/number.rs, src/verbs/maff.rs, src/verbs/mod.rs, tests/agreement.rs, tests/sanity_checks.rs
Add a slightly better math abstraction, where we can do things with a type (`Num`) which implements some operators, instead of macros, enabling at least slightly complex verbs to be implemented in one line.
I would bet there's bugs in the promotion rules for minus/divide/multiply, but they're currently useful enough?
=> feat: simple >: ("increment") implementation

src/arrays/elem.rs, src/arrays/mod.rs, src/arrays/owned.rs, src/cells.rs, src/scan/litnum.rs, src/scan/number.rs, src/verbs/maff.rs, src/verbs/mod.rs
Extension to the `Num` enum to cover the `Box` and `Char` cases. Use the new `Elem` type in all the array building code, so we drop the weird limitations there. Now `v_equal` and the like are simple to implement generically, with more `rank0` functions.
=> feat: Elem

src/arrays/cow.rs, src/arrays/mod.rs, src/arrays/owned.rs, src/bin/jr/main.rs, src/bin/jr/tui.rs, src/modifiers.rs, src/number/number.rs, src/number/promote.rs, src/scan/litnum.rs, src/scan/mod.rs, src/verbs/impl_impl.rs, src/verbs/impl_shape.rs, src/verbs/mod.rs
Fix all the non-controversial `cargo clippy` results, making the report a bit more readable.
=> chore: apply some clippy warning fixes

Cargo.lock, Cargo.toml, examples/ranky-ranks.rs, src/arrays/cow.rs, src/arrays/elem.rs, src/arrays/mod.rs, src/arrays/nd_ext.rs, src/arrays/owned.rs, src/arrays/plural.rs, src/cells.rs, src/empty.rs, src/lib.rs, src/modifiers/adverb.rs, src/modifiers/conj.rs, src/verbs/impl_impl.rs, src/verbs/impl_maths.rs, src/verbs/impl_shape.rs, src/verbs/mod.rs, tests/sanity_checks.rs, tests/smoke.ijs, tests/smoke.rs, tests/smoke.toml
I was trying to get `#/.~@/:~` to work. How hard can it be. It's EIGHT FUCKING CHARACTERS. FUCK ME.
We're about 10% of the way to an almost-working `/.`, which requires monad `=`, which requires monad `~.`, then the rest of the expression relies on `/:` being implemented on chars, which I haven't done.
--
Expedition notes, day 4, I think `=` and `~.` work, and I've beefed up (dyadic) `#`.
`(= 5 4 3 4 5) #@# 5 4 3 4 5` still won't behave (this is roughly what `#/.~` is trying to achieve, I think).
--
Expedition notes, day 6.
We found more of those impossibly bizarre hieroglyphs scratched into a wall:
https://code.jsoftware.com/wiki/File:Funcomp.png
With the assistance of two cute priests, we have managed to make a more complete attempt at `c_at`, but the code around ranks is now creaking …
=> feat: passive / reflexive / power / cat / sort / nub

Justfile, src/lib.rs, src/test_impls/jsoft_binary.rs, src/test_impls/jsoft_runs.rs, src/test_impls/mod.rs, src/verbs/impl_shape.rs, tests/smoke.ijs, tests/smoke.rs, tests/smoke.toml
This allows us to test boxes (FORESHADOWING), and gerunds, and the like. It's also 'faster' (as it runs J fewer times), at the expense a buttload of weird ass-code.
There's some more patches for this lying around but I think this is the bulk, and it's useful as it is (BOX TESTS!).
=> chore: test framework works based off the binary encoding

src/ctx/locales.rs, src/eval/mod.rs, src/foreign/files.rs, src/foreign/names.rs, src/scan/litnum.rs, tests/smoke.ijs, tests/smoke.toml
Remove all the regex pre-validation from the number code and go back to trusting the parser, seems to parse all the current tests, so why not, eh.
=> feat: support parsing nums-with-base (16bff)

Cargo.lock, src/eval/controls.rs, src/eval/mod.rs, src/foreign/conversion.rs, src/foreign/files.rs, src/foreign/host.rs, src/foreign/locales.rs, src/foreign/mod.rs, src/foreign/names.rs, src/foreign/scripts.rs, src/lib.rs, src/modifiers/conj.rs, src/modifiers/mod.rs, src/verbs/impl_impl.rs, src/verbs/mod.rs, src/verbs/partial.rs, src/verbs/primitive.rs, src/verbs/ranks.rs
Add a new `Partial` verb type, next to `Primitive` and `Anonymous`.
These verbs are the result of adverb and conjunction ... construction? Formation?
An adverb/conjunction forms into a verb, then that verb can be manipulated and executed. Logic can execute while this formation happens; this is not just a parser hack. (It's currently implemented in the parser, as a hack, but it won't be when everything has migrated).
This enables:
Partial execution of a foreign knows what it's doing:
```
18!:4
18!:4
```
```
19!:4
error: feature not supported yet
cause: unsupported major foreign: 19!:4
cause: evaluating "19!:4"
```
On main, this is not pre-validated:
```
19!:4
m !: n
```
And, foreigns can have ranks and lack monads or dyads like normal verbs:
```
2 (2!:5) 3
error: Kitchen sink error, you …
```
=> feat: de-catastrophe the foreigns

src/eval/mod.rs, src/foreign/mod.rs, src/lib.rs, src/modifiers/adverb.rs, src/modifiers/conj.rs, src/modifiers/mod.rs, src/verbs/impl_impl.rs
* adverbs are now "forming", they return partials.
* derivedadverbs are now forming too; they could only ever contain a conjunction(*), and act like a partially applied conjunction
* this removes the concept of derivedverbs(!)
I couldn't hit the Adverb Adverb matching so I have no idea what it's supposed to do, I've made it Error instead of fixing it.
=> feat: forming adverbs

src/eval/controls.rs, src/eval/semi.rs, src/modifiers/adverb.rs, src/modifiers/conj.rs, src/modifiers/mod.rs, src/verbs/impl_impl.rs, src/verbs/partial.rs
#146 but I didn't try and fix `v_append`.
Add some way to turn executable code back into displayable code, primarily for debug output? The jsoft implementation does a much better job of eliminating brackets.
=> feat: some space for generating names and something approaching debug output

docs/CONVERSION.md, examples/bench.rs, src/arrays/owned.rs, src/cells/flatten.rs, src/cells/mod.rs, src/modifiers/adverb.rs, src/number/mod.rs, src/number/promote.rs, src/scan/litnum.rs, src/verbs/impl_impl.rs, src/verbs/impl_shape.rs, src/verbs/mod.rs, tests/smoke.ijs, tests/smoke.toml
Finish moving people off `promote_to_array` onto `from_fill_promote` which should do roughly the same things, but the latter is probably more efficient. They probably aren't the same around atoms and type conversions, but none of the current tests seem to care.
=> feat: move everyone away from the legacy fill code and delete it

src/arrays/word.rs, src/eval/semi.rs, src/verbs/impl_impl.rs
```
aaron@Aarons-Air jr % cargo run
Compiling jr v0.1.0 (/Users/aaron/codebases/jr)
Finished dev [unoptimized + debuginfo] target(s) in 1.50s
Running `target/debug/jr`
jr 0.1.0
f=: 3 : 0
NB. comment
2 * y
)
(3 : '
2 * y 
')
f
(3 : '
2 * y 
')
```
TODO: Carry a sourcefile and line number reference in (or for?) each `Word::Verb()` instance to allow Word::fmt::Display to show original source including comments when necessary. (repl log would likely be a virtual file...)
=> fix: display verb names

src/ctx/mod.rs, src/foreign/mod.rs, src/foreign/scripts.rs
Script names and file contents are carried in the Ctx. File contents are kept so we can render original verb/conj/adv definitions eventually.
=> feat: 4!:3 script names foreign
