AshyIsMe/jr

src/lib.rs, tests/edge_cases.rs
Add error returns for some cases which currently crash.
=> fix: survive 60s of fuzzing

src/lib.rs
What's the correct syntax to match or `if let ...` for specific enum variants in `v_d_plus()`?
=> wip: first attempt at eval

src/lib.rs, tests/edge_cases.rs
First rough attempt at a lookup table for verb functions.
Currently not compiling.
=> feat: verb fn hashmap

.github/workflows/rust.yml
lit. fig. just the template, so you can spend your credits.
=> chore: basic CI on gith-ub

Cargo.lock, src/arrays.rs, src/modifiers.rs, src/scan.rs, src/verbs.rs, tests/edge_cases.rs, tests/sanity_checks.rs
=> chore: anonymise array field

src/arrays.rs, src/bin/jr.rs, src/eval.rs
First pass attempt at a Display implementation for `Word` and `JArray`.
It's nicer than the Debug when using the jr repl but not even close to j's output style yet.
=> Draft: wip: display

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/arrays.rs, src/bin/jr.rs, src/eval.rs, src/modifiers.rs, src/scan.rs, src/verbs.rs, tests/edge_cases.rs, tests/errors.rs
With the stabilisation of `backtrace`, not using `anyhow` is almost criminal.
=> chore: std -> anyhow

src/arrays.rs, src/lib.rs, src/modifiers.rs, src/scan.rs, src/verbs.rs, tests/sanity_checks.rs
Add rationals, and change ExtInt to bigint. Fake and lie about the promotion, we don't actually have promotion yet.
=> feat: num doms

src/cells.rs, src/lib.rs
A bunch of code which might look like a cells implementation, with tests, but not used anywhere.
=> chore: add Faux' cells impl, unused

src/lib.rs, src/verbs/mod.rs, src/verbs/ranks.rs
Add a bunch of rank definitions to our Primitive (nee. Simple) verb implementations.
=> chore: add rank definitions

src/arrays/owned.rs, src/cells.rs, src/verbs/mod.rs, src/verbs/ranks.rs, tests/agreement.rs, tests/sanity_checks.rs
Trying to pull some of the code out of #61 that doesn't break any tests, to make the diff a bit more reviewable.
=> chore: a bunch of code to support the agreement branch, take two

src/arrays/owned.rs, src/cells.rs, src/eval.rs, src/lib.rs, src/modifiers.rs, src/scan.rs, src/verbs/mod.rs, src/verbs/ranks.rs, tests/sanity_checks.rs
I started writing a `quote` / `rank` / `"` impl. I don't know if it's correct, I don't really care.
I discovered that we can't parse `_` (`infinity`), so we can't type out ranks.
I then discovered that we can't parse `1 _ 1`, as it's bool/float/bool, which the code doesn't handle.
So I went and fixed non-homo array parsing with some promotion. I think. There's a number of tests which pass.
~I still didn't fix parsing infinity, and I don't plan to, ha ha ha.~ I fixed like six cases of parsing infinity and I hate everyone. `__j__`. Just no. NO NO NO.
=> feat: quote and promo

src/arrays/cow.rs, src/cells.rs, src/verbs/mod.rs, tests/agreement.rs, tests/sanity_checks.rs
Merge yet more of the `fix/agreement` branch; the stuff that doesn't break any existing tests.
=> chore: more green fix/agreement code

src/arrays/owned.rs, src/cells.rs, src/scan/litnum.rs, src/scan/mod.rs, src/scan/number.rs
Non-controversial code stolen from #74.
=> chore: bits of #74 which are generic helpers

examples/ranky-ranks.rs, src/arrays/owned.rs, src/cells.rs, src/lib.rs, src/modifiers.rs, src/verbs/mod.rs, tests/agreement.rs, tests/sanity_checks.rs
Faux' 73rd attempt at agreement, and 74th attempt at guessing PR numbers wrong.
I think I've got most of the tests from #61, and some of the followup code in #66 , but everything is now such a mess it's getting hard to see. This passes a bunch of known tests, and is primarily only varying in `cells.rs`, so I don't feel too bad merging it.
=> fix: agreement take 73

src/verbs/mod.rs
https://www.jsoftware.com/help/dictionary/d130.htm
I thought this would be enough for test_fork_average, but it's not, 'cos we don't implement monadic verb ranks yet.
=> feat: implement some of monadic #

src/cells.rs, src/modifiers.rs, src/scan/number.rs, src/verbs/mod.rs, tests/agreement.rs, tests/sanity_checks.rs
Honour verb rank when calling monadic functions.
Fixup rank " a bit.
=> feat: monadic apply + rank

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/lib.rs, src/scan/number.rs, src/verbs/maff.rs, src/verbs/mod.rs
Implement some boring rank-0 monads.
=> feat: deal

src/arrays/owned.rs, src/number/number.rs, src/verbs/mod.rs, tests/sanity_checks.rs
..and abuse the shit out of its code.
=> fix: take's insane handling of atoms / single element lists

src/verbs/impl_impl.rs, src/verbs/impl_maths.rs, src/verbs/impl_shape.rs, src/verbs/mod.rs
Just to get the file length down a bit.
I tried to make it vaguely rational but there's probably some mistakes. Can just move them back later.
IntelliJ was giving up on the 1,000+ line file.
=> chore: split verbs/mod

src/lib.rs, src/modifiers/conj.rs, tests/sanity_checks.rs
Stupidly simple first pass at the `4 : 'x + y'` style user defined verbs.
https://code.jsoftware.com/wiki/Vocabulary/cor
=> feat: user defined dyadic verbs

src/arrays/elem.rs, src/arrays/owned.rs, src/cells.rs, src/eval.rs, src/lib.rs, src/modifiers/adverb.rs, src/modifiers/conj.rs, src/plot/mod.rs, src/verbs/impl_impl.rs, src/verbs/impl_maths.rs, src/verbs/impl_shape.rs, src/verbs/maff.rs, src/verbs/mod.rs, tests/sanity_checks.rs
Main complication here is VerbImpl#exec() now errors if you call a derivedverb containing an adverb, which may be incorrect.
=> chore: verbs produce nouns

Cargo.lock, Cargo.toml, Justfile, examples/gen-runlist.rs, src/bin/jr/main.rs, src/bin/jr/tui.rs, src/ctx/mod.rs, src/error.rs, src/eval.rs, src/lib.rs, src/modifiers/conj.rs, src/modifiers/mod.rs, src/test_impls/jsoft_runs.rs, src/test_impls/mod.rs, tests/errors.rs, tests/smoke.ijs, tests/smoke.rs, tests/smoke.toml
Implement a small part of `0 : 0`.
Yes, that thing.
=> war crimes: `: 0`

Cargo.lock, src/verbs/impl_impl.rs
Remove some of the Interesting error handling and "// I promise it's okay"s from the parallel fork code.
=> feat: parallel fork fiddling
